apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-platform
  annotations:
    # External Secrets Operator CRD가 준비된 뒤 적용되어야 합니다.
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    vault:
      server: http://onprem-vault.vault.svc:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
