# cert-manager CRD를 Helm release와 함께 관리합니다.
installCRDs: true

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true

prometheus:
  enabled: true
