apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-actions-runner-controller
  namespace: argocd
  annotations:
    # Runner scale set보다 먼저 ARC operator와 CRD를 설치합니다.
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.14.2
      helm:
        releaseName: arc
        valueFiles:
          - $values/03-k8s-clusters/onprem/values/actions-runner-controller-values.yaml
    - repoURL: https://github.com/Son-Hunseo/My-IaC-GitOps
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
