apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-external-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://github.com/Son-Hunseo/My-GitAIOps
    targetRevision: main
    path: 03-k8s-clusters/onprem/overlays/external-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m
