apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onprem-gateway-api-crds
  namespace: argocd
  annotations:
    # NGINX Gateway Fabric 설치 전에 표준 Gateway API CRD를 먼저 설치합니다.
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/nginx/nginx-gateway-fabric.git
    targetRevision: v2.6.3
    path: config/crd/gateway-api/standard
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
