apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - apps/cert-manager.yaml
  - apps/external-secrets.yaml
  - apps/nfs-subdir-external-provisioner.yaml
  - apps/gateway-api-crds.yaml
  - apps/prometheus.yaml
  - apps/grafana.yaml
  - apps/metallb.yaml
  - apps/nginx-gateway-fabric.yaml
  - apps/vault.yaml
  - apps/metallb-config.yaml
  - apps/external-secrets-vault-store.yaml
  - apps/harbor-secrets.yaml
  - apps/harbor.yaml
  - apps/github-runner-auth.yaml
  - apps/cluster-issuer.yaml
  - apps/actions-runner-controller.yaml
  - apps/github-runner-scale-set.yaml
  - apps/internal-gateway.yaml
  - apps/external-gateway.yaml
  - apps/nas.yaml
