apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-platform
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: platform/harbor/system
        property: admin-password
    - secretKey: secretKey
      remoteRef:
        key: platform/harbor/system
        property: secret-key
    - secretKey: secret
      remoteRef:
        key: platform/harbor/system
        property: core-secret
    - secretKey: CSRF_KEY
      remoteRef:
        key: platform/harbor/system
        property: csrf-key
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: platform/harbor/system
        property: jobservice-secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: platform/harbor/system
        property: registry-http-secret
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: platform/harbor/system
        property: registry-password
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: platform/harbor/system
        property: registry-htpasswd
    - secretKey: tls.key
      remoteRef:
        key: platform/harbor/system
        property: token-tls-key
    - secretKey: tls.crt
      remoteRef:
        key: platform/harbor/system
        property: token-tls-crt
