apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-platform
    kind: ClusterSecretStore
  target:
    name: route53-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: platform/route53
        property: access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: platform/route53
        property: secret-access-key
