# AWS Secrets Manager 연동은 IRSA를 사용하며 access key를 values에 넣지 않습니다.
installCRDs: true

serviceAccount:
  create: true
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::211125633965:role/gitops-eks-dev-external-secrets-role

webhook:
  port: 9443
